### ISSUE TITLE
Wathcer logo offer

### ISSUE THREAD

**Issue by furkan-firat** [faustinoaq/watcher#7]
Hi sir. I want to contribute for watcher. I degined a logo for readme file.

Logo Idea: watch file changes... If you want it, i will send a pull-request. Please fedback me. Good works!

![watcher](https://user-images.githubusercontent.com/40358165/41536389-24f9fc24-730e-11e8-809a-7b26b9137086.png)

**Comment by faustinoaq** [comment]
Awesome!!! :tada:

**Comment by furkan-firat** [comment]
I sent the all variantion files. https://github.com/faustinoaq/watcher/pull/8 Please checkt it :)
